### ISSUE TITLE
[did-configuration] Provide complete JWT examples

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/well-known#1]
Can use https://github.com/decentralized-identity/lds-ecdsa-secp256k1-2019.js/tree/master/packages/es256k-jws-ts

All JWTs should be verifiable, and all properties should be defined.

**Comment by OR13** [comment]
I think the top level JWT should be sign-able by non DIDs.

**Comment by OR13** [comment]
Implemented a demo: https://github.com/decentralized-identity/well-known/pull/2

decided not to sign the top level object.

**Comment by ipatka** [comment]
Nice! I reviewed the implementation and I was able to run the demo locally
<img width="577" alt="Screen Shot 2019-08-06 at 7 52 20 PM" src="https://user-images.githubusercontent.com/4401444/62585118-39b78380-b885-11e9-902b-9a73dfc95821.png">
![Screen Shot 2019-08-06 at 7 52 14 PM](https://user-images.githubusercontent.com/4401444/62585119-39b78380-b885-11e9-8745-e4e767d235b6.png)

What do you mean by the following?

> The demo opens up more questions about what "verification" of claims mean.

**Comment by OR13** [comment]
awesome! 

The claim in the JWT has a domain field. here is some pseudo code explaining how verification should work.

```
config = GET JSON ( https://example.com/.well-known/did-configuration )
For each claim in config:
- verify claim was signed by did listed in config (use resolver to get public keys)
- verify that domain in claim matches "example.com"

In the demo provided, there is no check for the last bit.

I would expect the demo to fail or warn when running on localhost.

```

**Comment by ipatka** [comment]
Oh I see. What if on the client side it just checked if verified.domain matches window.location.hostname?

**Comment by OR13** [comment]
Thats a good idea for self requests, but the client is always going to need to trust its own web server, and this spec should theoretically support CORs, where:

example.com has DIDs and can trust api.example2.com's DIDs.

the origin of a well-known did config should be present in each of the claims as the domain field.

That way 2 servers can use this for mutual auth if they wanted to.

**Comment by OR13** [comment]
I'm gonna close this now that the example is merged. Feel free to open new issues with concerns / questions/
